//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contact_Tracking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contact_Tracking.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Visit.
        /// </summary>
        public static string AddVisit {
            get {
                return ResourceManager.GetString("AddVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Group.
        /// </summary>
        public static string AgeGroup {
            get {
                return ResourceManager.GetString("AgeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corona Proof.
        /// </summary>
        public static string CoronaProof {
            get {
                return ResourceManager.GetString("CoronaProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covid.
        /// </summary>
        public static string Covid {
            get {
                return ResourceManager.GetString("Covid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested and Vaccinated Status can be saved so that visitors don&apos;t have to show their proof every time..
        /// </summary>
        public static string CovidDescription {
            get {
                return ResourceManager.GetString("CovidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR.
        /// </summary>
        public static string CreateQR {
            get {
                return ResourceManager.GetString("CreateQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to save.
        /// </summary>
        public static string DaysToSave {
            get {
                return ResourceManager.GetString("DaysToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to show.
        /// </summary>
        public static string DaysToShow {
            get {
                return ResourceManager.GetString("DaysToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Person.
        /// </summary>
        public static string DeletePerson {
            get {
                return ResourceManager.GetString("DeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queer.
        /// </summary>
        public static string divers {
            get {
                return ResourceManager.GetString("divers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Download is complete!
        ///
        ///Would you like to install now?.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Camera.
        /// </summary>
        public static string FlipCamera {
            get {
                return ResourceManager.GetString("FlipCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new.
        /// </summary>
        public static string GenerateNew {
            get {
                return ResourceManager.GetString("GenerateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the fonts we installed just now the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        public static string InstalledFonts {
            get {
                return ResourceManager.GetString("InstalledFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Visitors.
        /// </summary>
        public static string MaxVisists {
            get {
                return ResourceManager.GetString("MaxVisists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migration background.
        /// </summary>
        public static string migration_background {
            get {
                return ResourceManager.GetString("migration_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require Proof at Age.
        /// </summary>
        public static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Restart.
        /// </summary>
        public static string NoRestart {
            get {
                return ResourceManager.GetString("NoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data gets encrypted and saved in a data base using your unique security key..
        /// </summary>
        public static string PersonalDataDescription {
            get {
                return ResourceManager.GetString("PersonalDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string PersonalID {
            get {
                return ResourceManager.GetString("PersonalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require password to edit people.
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Changes.
        /// </summary>
        public static string ResetChanges {
            get {
                return ResourceManager.GetString("ResetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the language settings the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        public static string Restart_Language {
            get {
                return ResourceManager.GetString("Restart_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Statistic.
        /// </summary>
        public static string SaveStats {
            get {
                return ResourceManager.GetString("SaveStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Visitors.
        /// </summary>
        public static string SaveVisitors {
            get {
                return ResourceManager.GetString("SaveVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically search for Updates.
        /// </summary>
        public static string SearchForUpdates {
            get {
                return ResourceManager.GetString("SearchForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform several actions you will be required to have a password set.
        ///All data stored through this software is encrypted using your unique security key. Changing this key means all QR Codes you handed out won&apos;t work anymore..
        /// </summary>
        public static string SecurityDescription {
            get {
                return ResourceManager.GetString("SecurityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Key.
        /// </summary>
        public static string SecurityKey {
            get {
                return ResourceManager.GetString("SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tooltips.
        /// </summary>
        public static string Show_ToolTips {
            get {
                return ResourceManager.GetString("Show_ToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply the tooltip settings the application has to be restarted 
        ///
        ///Restart now?.
        /// </summary>
        public static string Show_ToolTips_Changed {
            get {
                return ResourceManager.GetString("Show_ToolTips_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Badge.
        /// </summary>
        public static string ShowBadge {
            get {
                return ResourceManager.GetString("ShowBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split log.
        /// </summary>
        public static string SplitLog {
            get {
                return ResourceManager.GetString("SplitLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split log at (24h).
        /// </summary>
        public static string SplitLogAt {
            get {
                return ResourceManager.GetString("SplitLogAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Statistics.
        /// </summary>
        public static string SplitStats {
            get {
                return ResourceManager.GetString("SplitStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split stats at (24h).
        /// </summary>
        public static string SplitStatsAt {
            get {
                return ResourceManager.GetString("SplitStatsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits can be gathered anonymously to create easy Statistics.
        ///The statistics saves only:
        ///- Age
        ///- Gender
        ///- Migration Background.
        /// </summary>
        public static string StatDescription {
            get {
                return ResourceManager.GetString("StatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested.
        /// </summary>
        public static string Tested {
            get {
                return ResourceManager.GetString("Tested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tested (hours).
        /// </summary>
        public static string TestedDuration {
            get {
                return ResourceManager.GetString("TestedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Tracking {
            get {
                return ResourceManager.GetString("Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to your.
        /// </summary>
        public static string ttp_Browse {
            get {
                return ResourceManager.GetString("ttp_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Folder your Data for the application is stored in..
        /// </summary>
        public static string ttp_DataPath {
            get {
                return ResourceManager.GetString("ttp_DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new.
        /// </summary>
        public static string ttp_New {
            get {
                return ResourceManager.GetString("ttp_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not reach the github repo. Please check your internet connection!.
        /// </summary>
        public static string ttp_NoInternet {
            get {
                return ResourceManager.GetString("ttp_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your settings to the default settings..
        /// </summary>
        public static string ttp_Reset {
            get {
                return ResourceManager.GetString("ttp_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available, please update!.
        /// </summary>
        public static string ttp_UpdateAvailable {
            get {
                return ResourceManager.GetString("ttp_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Update was downloaded already but not installed!
        ///
        ///Install it now?.
        /// </summary>
        public static string UpdateInstall {
            get {
                return ResourceManager.GetString("UpdateInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available!
        ///
        ///Would you like to update?.
        /// </summary>
        public static string UpdatePopUp {
            get {
                return ResourceManager.GetString("UpdatePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccinated.
        /// </summary>
        public static string Vaccinated {
            get {
                return ResourceManager.GetString("Vaccinated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccinated (Days).
        /// </summary>
        public static string VaccinatedDuration {
            get {
                return ResourceManager.GetString("VaccinatedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string Visitors {
            get {
                return ResourceManager.GetString("Visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Stats.
        /// </summary>
        public static string VisitorStats {
            get {
                return ResourceManager.GetString("VisitorStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Tracking.
        /// </summary>
        public static string VisitorTracking {
            get {
                return ResourceManager.GetString("VisitorTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors can be stored in a encrypted data base using your unique security key.
        ///
        ///If you don&apos;t enable saving visits in the data base they will get lost if you restart the program..
        /// </summary>
        public static string VisitsDescription {
            get {
                return ResourceManager.GetString("VisitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe People.
        /// </summary>
        public static string WipePeople {
            get {
                return ResourceManager.GetString("WipePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Statistic.
        /// </summary>
        public static string WipeStats {
            get {
                return ResourceManager.GetString("WipeStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe Visitor Logs.
        /// </summary>
        public static string WipeVisits {
            get {
                return ResourceManager.GetString("WipeVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
